# Default values for mono.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#Name
name: insighttellers-web

#Replica
replicaCount: 1

#Images
image:
  repository: ni3devops/inisghttellers
  tag: a-------------------------------9
  pullPolicy: Always

#ImageSecrets:
imagePullSecrets:
        - name: dockerregistry

#PodsSecurityContext
securityContext:
  privileged: false

nginx:
  enabled: false
  resources:
    requests:
      cpu: 500m
    limits:
      cpu: 500m

#Stack
stack: 1-----1       
